services:
    api:
        container_name: api
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
        volumes:
            - ./:/app
        ports:
            - 9000:8080
        depends_on:
            - database_mysql
            # - database_pgsql
            # - redis
    database_mysql:
        container_name: database_mysql
        image: mysql:8.0
        ports:
            -   3306:3306
        environment:
            - MYSQL_DATABASE=default
            - MYSQL_USER=laravel
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=secret
        volumes:
            - db-data:/var/lib/mysql
    # database_pgsql:
    #     container_name: database_pgsql
    #     image: postgres:latest
    #     ports:
    #     - 5432:5432
    #     environment:
    #     - POSTGRES_DB=default
    #     - POSTGRES_USER=laravel
    #     - POSTGRES_PASSWORD=secret
    #     volumes:
    #     - pg-data:/var/lib/postgresql/data
    # redis:
    #     container_name:  redis
    #     image: redis:alpine
    #     command: redis-server --appendonly yes --requirepass  "secret"
    #     ports:
    #     - 6380:6379
volumes:
    db-data:
    pg-data:
